// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYFBBOkWpheH_zsnLJ0Ou4SyP-hE4x8I',
    appId: '1:458897946123:web:7cab655947c88ead38790e',
    messagingSenderId: '458897946123',
    projectId: 'ateliermandala-2ead9',
    authDomain: 'ateliermandala-2ead9.firebaseapp.com',
    storageBucket: 'ateliermandala-2ead9.appspot.com',
    measurementId: 'G-RM4KGS2GW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40s3-eS1OAzClQE2MxrbUL2xxfAESqkE',
    appId: '1:458897946123:android:d414f4819e0b176e38790e',
    messagingSenderId: '458897946123',
    projectId: 'ateliermandala-2ead9',
    storageBucket: 'ateliermandala-2ead9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVVReN_S5IoDwIkEEyT45a2ODHJoHbJA',
    appId: '1:458897946123:ios:9054099a4e91ca2738790e',
    messagingSenderId: '458897946123',
    projectId: 'ateliermandala-2ead9',
    storageBucket: 'ateliermandala-2ead9.appspot.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgVVReN_S5IoDwIkEEyT45a2ODHJoHbJA',
    appId: '1:458897946123:ios:9054099a4e91ca2738790e',
    messagingSenderId: '458897946123',
    projectId: 'ateliermandala-2ead9',
    storageBucket: 'ateliermandala-2ead9.appspot.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuYFBBOkWpheH_zsnLJ0Ou4SyP-hE4x8I',
    appId: '1:458897946123:web:d9dc2b5f2933a77a38790e',
    messagingSenderId: '458897946123',
    projectId: 'ateliermandala-2ead9',
    authDomain: 'ateliermandala-2ead9.firebaseapp.com',
    storageBucket: 'ateliermandala-2ead9.appspot.com',
    measurementId: 'G-2G87BNDK96',
  );
}
